---
- name: Create backup script
  template:
    src: backup.sh.j2
    dest: "{{ install_dir }}/backup.sh"
    owner: root
    group: root
    mode: '0755'

- name: Schedule backups
  cron:
    name: "SMTP server backup"
    minute: "{{ backup_schedule.split()[0] }}"
    hour: "{{ backup_schedule.split()[1] }}"
    day: "{{ backup_schedule.split()[2] }}"
    month: "{{ backup_schedule.split()[3] }}"
    weekday: "{{ backup_schedule.split()[4] }}"
    job: "{{ install_dir }}/backup.sh >> {{ log_dir }}/backup.log 2>&1"
    user: "{{ deploy_user }}"

- name: Create backup cleanup script
  template:
    src: backup-cleanup.sh.j2
    dest: "{{ install_dir }}/backup-cleanup.sh"
    owner: root
    group: root
    mode: '0755'

- name: Schedule backup cleanup
  cron:
    name: "SMTP backup cleanup"
    minute: "0"
    hour: "4"
    job: "{{ install_dir }}/backup-cleanup.sh"
    user: "{{ deploy_user }}"
