---
- name: Ensure database directory exists
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: '0750'

- name: Check database integrity
  command: sqlite3 {{ db_path }} "PRAGMA integrity_check;"
  register: db_integrity
  changed_when: false
  failed_when: db_integrity.stdout != "ok"
  when: db_stat.stat.exists | default(false)

- name: Backup database daily
  cron:
    name: "Backup SMTP database"
    minute: "0"
    hour: "3"
    job: "sqlite3 {{ db_path }} '.backup {{ backup_dir }}/smtp-$(date +\\%Y\\%m\\%d).db'"
    user: "{{ deploy_user }}"
  when: backup_enabled
