---
- name: Configure UFW (Debian/Ubuntu)
  block:
    - name: Allow SMTP port
      ufw:
        rule: allow
        port: "{{ smtp_port }}"
        proto: tcp

    - name: Allow health check port
      ufw:
        rule: allow
        port: "{{ health_port }}"
        proto: tcp
        from_ip: 127.0.0.1

    - name: Allow metrics port
      ufw:
        rule: allow
        port: "{{ metrics_port }}"
        proto: tcp
        from_ip: 127.0.0.1

    - name: Enable UFW
      ufw:
        state: enabled
  when: ansible_os_family == "Debian"

- name: Configure firewalld (RedHat/CentOS)
  block:
    - name: Allow SMTP port
      firewalld:
        port: "{{ smtp_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes

    - name: Reload firewalld
      systemd:
        name: firewalld
        state: reloaded
  when: ansible_os_family == "RedHat"
