---
- name: Download SMTP server binary
  get_url:
    url: "{{ smtp_binary_url }}"
    dest: "{{ install_dir }}/smtp-server"
    mode: '0755'
    owner: root
    group: root
  notify: restart smtp-server

- name: Download user CLI binary
  get_url:
    url: "{{ smtp_cli_url }}"
    dest: "{{ install_dir }}/user-cli"
    mode: '0755'
    owner: root
    group: root

- name: Create symlinks in /usr/local/bin
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "{{ install_dir }}/smtp-server", dest: "/usr/local/bin/smtp-server" }
    - { src: "{{ install_dir }}/user-cli", dest: "/usr/local/bin/user-cli" }

- name: Check if database exists
  stat:
    path: "{{ db_path }}"
  register: db_stat

- name: Initialize database
  command: "{{ install_dir }}/user-cli init-db"
  environment:
    SMTP_DB_PATH: "{{ db_path }}"
  when: not db_stat.stat.exists

- name: Set database permissions
  file:
    path: "{{ db_path }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: '0600'
