---
- name: Include prerequisites
  include_tasks: prerequisites.yml
  tags: [prerequisites]

- name: Include user setup
  include_tasks: user.yml
  tags: [user]

- name: Include installation
  include_tasks: install.yml
  tags: [install]

- name: Include configuration
  include_tasks: configure.yml
  tags: [configure]

- name: Include TLS setup
  include_tasks: tls.yml
  tags: [tls]
  when: smtp_enable_tls

- name: Include database setup
  include_tasks: database.yml
  tags: [database]

- name: Include firewall configuration
  include_tasks: firewall.yml
  tags: [firewall]
  when: configure_firewall

- name: Include backup configuration
  include_tasks: backup.yml
  tags: [backup]
  when: backup_enabled

- name: Include monitoring setup
  include_tasks: monitoring.yml
  tags: [monitoring]

- name: Include systemd service
  include_tasks: service.yml
  tags: [service]
