---
- name: Create health check script
  template:
    src: health-check.sh.j2
    dest: "{{ install_dir }}/health-check.sh"
    owner: root
    group: root
    mode: '0755'

- name: Schedule health checks
  cron:
    name: "SMTP health check"
    minute: "*/5"
    job: "{{ install_dir }}/health-check.sh >> {{ log_dir }}/health.log 2>&1"
    user: "{{ deploy_user }}"

- name: Install node_exporter for Prometheus
  block:
    - name: Download node_exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz

    - name: Extract node_exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /usr/local/bin
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Create node_exporter systemd service
      template:
        src: node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: '0644'

    - name: Start node_exporter
      systemd:
        name: node_exporter
        state: started
        enabled: yes
        daemon_reload: yes
  when: enable_prometheus
