---
- name: Update apt cache (Debian/Ubuntu)
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install required packages (Debian/Ubuntu)
  apt:
    name:
      - curl
      - ca-certificates
      - sqlite3
      - ufw
      - logrotate
    state: present
  when: ansible_os_family == "Debian"

- name: Install required packages (RedHat/CentOS)
  yum:
    name:
      - curl
      - ca-certificates
      - sqlite
      - firewalld
      - logrotate
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure required directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ install_dir }}"
    - "{{ data_dir }}"
    - "{{ queue_dir }}"
    - "{{ mail_dir }}"
    - "{{ log_dir }}"
    - "{{ config_dir }}"
    - "{{ config_dir }}/tls"
    - "{{ backup_dir }}"
