---
- name: Create systemd service file
  template:
    src: smtp-server.service.j2
    dest: /etc/systemd/system/smtp-server.service
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd

- name: Enable and start SMTP server service
  systemd:
    name: smtp-server
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for service to be ready
  wait_for:
    port: "{{ smtp_port }}"
    delay: 2
    timeout: 30

- name: Verify service is healthy
  uri:
    url: "http://localhost:{{ health_port }}/health"
    return_content: yes
  register: health_response
  failed_when: health_response.status != 200
