---
- name: Check if TLS certificate exists
  stat:
    path: "{{ tls_cert_path }}"
  register: tls_cert_stat

- name: Generate self-signed certificate
  command: >
    openssl req -x509 -newkey rsa:4096 -keyout {{ tls_key_path }}
    -out {{ tls_cert_path }} -days 365 -nodes
    -subj "/C=US/ST=State/L=City/O=Organization/CN={{ smtp_hostname }}"
  when: tls_auto_generate and not tls_cert_stat.stat.exists

- name: Set TLS certificate permissions
  file:
    path: "{{ item.path }}"
    owner: root
    group: "{{ deploy_group }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ tls_cert_path }}", mode: '0644' }
    - { path: "{{ tls_key_path }}", mode: '0640' }
  when: tls_cert_stat.stat.exists or tls_auto_generate
