apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smtp-data-pvc
  namespace: smtp-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Adjust based on your cluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smtp-queue-pvc
  namespace: smtp-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
