---
# SMTP Server Configuration
smtp_version: "latest"
smtp_binary_url: "https://github.com/your-org/smtp-server/releases/download/{{ smtp_version }}/smtp-server-linux-x86_64"
smtp_cli_url: "https://github.com/your-org/smtp-server/releases/download/{{ smtp_version }}/user-cli-linux-x86_64"

# Service Configuration
smtp_port: 25
smtp_hostname: "{{ ansible_fqdn }}"
smtp_max_connections: 100
smtp_max_message_size: 26214400  # 25 MB
smtp_max_recipients: 100
smtp_enable_tls: true
smtp_enable_auth: true
smtp_enable_dnsbl: true
smtp_enable_greylist: true

# Directories
install_dir: /opt/smtp-server
data_dir: /var/lib/smtp-server
queue_dir: "{{ data_dir }}/queue"
mail_dir: "{{ data_dir }}/mail"
log_dir: /var/log/smtp-server
config_dir: /etc/smtp-server

# User & Group
deploy_user: smtp
deploy_group: smtp
deploy_uid: 2525
deploy_gid: 2525

# TLS Certificates
tls_cert_path: "{{ config_dir }}/tls/cert.pem"
tls_key_path: "{{ config_dir }}/tls/key.pem"
tls_auto_generate: true

# Database
db_path: "{{ data_dir }}/smtp.db"

# Monitoring
health_port: 8080
metrics_port: 8081
enable_prometheus: true
enable_statsd: false
statsd_host: "localhost"
statsd_port: 8125

# Backup
backup_enabled: true
backup_dir: "{{ data_dir }}/backups"
backup_retention_days: 30
backup_schedule: "0 2 * * *"  # Daily at 2 AM

# Firewall
configure_firewall: true
allowed_ips: []  # Empty = allow all

# Systemd
restart_on_failure: true
restart_delay_sec: 10

# Logging
log_level: INFO
log_max_size: 100M
log_max_backups: 10
