---
all:
  children:
    smtp_servers:
      hosts:
        smtp-staging.example.com:
          ansible_host: 192.168.2.10
          ansible_user: deploy
      vars:
        environment: staging
        smtp_port: 2525
        smtp_max_connections: 50
        smtp_max_message_size: 26214400  # 25 MB

  vars:
    ansible_python_interpreter: /usr/bin/python3
    deploy_user: smtp
    deploy_group: smtp
    install_dir: /opt/smtp-server
    data_dir: /var/lib/smtp-server
    log_dir: /var/log/smtp-server
