---
- name: restart smtp-server
  systemd:
    name: smtp-server
    state: restarted
    daemon_reload: yes

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: reload smtp-server
  systemd:
    name: smtp-server
    state: reloaded
