---
- name: Deploy SMTP Server
  hosts: smtp_servers
  become: yes
  roles:
    - smtp-server

  pre_tasks:
    - name: Gather facts
      setup:

    - name: Display deployment information
      debug:
        msg: "Deploying SMTP server version {{ smtp_version }} to {{ inventory_hostname }}"

  post_tasks:
    - name: Verify deployment
      uri:
        url: "http://{{ ansible_host }}:{{ health_port }}/health"
        return_content: yes
      register: health_check
      delegate_to: localhost

    - name: Display health status
      debug:
        msg: "Health check: {{ health_check.content }}"
